name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - fix/typed-decode-errors
  pull_request:
  workflow_dispatch:

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.24.x", "1.25.x", "1.26.x" ]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
